language: python

cache: pip

matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: required

install:
    - pip install --upgrade setuptools pip
    - pip install -r src/requirements.txt -r src/requirements/dev.txt -r src/requirements-tileserver.txt -r src/requirements/opengl.txt

before_script:
    - cd src

script:
    - flake8 c3nav
    - isort -c -rc .
    - python manage.py migrate
    - python manage.py collectstatic --noinput
    - python manage.py compress
